"""Catalogue items seeder data.

This file contains the initial catalogue items to be seeded into the database.
Data is sourced from docs/plans/global-catalogue-items.md
"""

# Mapping of item names to image filenames
CATALOGUE_ITEM_IMAGES = {
    "Swedish FireSteel 2.0": "light_my_fire_firesteel_2.0.jpg",
    "5.11 Rush 24": "5.11_rush_24.png",
    "Black Diamond Storm Headlamp": "black_diamond_storm_450.jpg",
    "Fenix PD35 V3.0": "fenix_pd35v3_flashlight.webp",
    "Anker PowerCore 20100": "anker_powercore_20100.png",
}

CATALOGUE_ITEMS = [
    # Ogień / Fire
    {
        "name": "Swedish FireSteel 2.0",
        "category": "fire",
        "brand": "Light My Fire",
        "model": "Swedish FireSteel 2.0",
        "description": "Krzesiwo ferrocerowe, niezawodne w trudnych warunkach",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "BIC Classic Lighter",
        "category": "fire",
        "brand": "BIC",
        "model": "Classic",
        "description": "Prosta i tania zapalniczka jednorazowa",
        "price_tier": "budget",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    # Noże / Narzędzia tnące
    {
        "name": "Fiskars X7",
        "category": "tools",
        "brand": "Fiskars",
        "model": "X7",
        "description": "Lekka, kompaktowa siekierka turystyczna / survivalowa",
        "price_tier": "budget",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    # Narzędzia wielofunkcyjne
    {
        "name": "Leatherman Wave+",
        "category": "tools",
        "brand": "Leatherman",
        "model": "Wave+",
        "description": "Uniwersalny multitool klasy premium",
        "price_tier": "premium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Leatherman Blast",
        "category": "tools",
        "brand": "Leatherman",
        "model": "Blast",
        "description": "Solidny multitool z pełnym zestawem narzędzi",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Gerber E-Tool Folding Shovel",
        "category": "tools",
        "brand": "Gerber",
        "model": "E-Tool Folding Shovel",
        "description": "Składana saperka terenowa",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Paracord 550 MIL-SPEC",
        "category": "tools",
        "brand": "Generic / MIL-SPEC",
        "model": "Paracord 550",
        "description": "Uniwersalna linka ratunkowa / survivalowa",
        "price_tier": "budget",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Paracord (Badger / MIL-SPEC)",
        "category": "tools",
        "brand": "Badger",
        "model": "Paracord 550",
        "description": "Mocna linka survivalowa / ratunkowa",
        "price_tier": "budget",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Gorilla Tape",
        "category": "tools",
        "brand": "Gorilla Tape",
        "model": "Gorilla Tape Standard",
        "description": "Uniwersalna, mocna taśma naprawcza do terenu",
        "price_tier": "budget",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "BAHCO 396-LAP",
        "category": "tools",
        "brand": "BAHCO",
        "model": "396-LAP",
        "description": "Składana piła ręczna, idealna do cięcia drewna w terenie",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Victorinox Ranger",
        "category": "tools",
        "brand": "Victorinox",
        "model": "Ranger",
        "description": "Szwajcarski scyzoryk z wieloma funkcjami, idealny do outdoor",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Victorinox Alox Bantam - Silver",
        "category": "tools",
        "brand": "Victorinox",
        "model": "Alox Bantam - Silver",
        "description": "Ultra-kompaktowy scyzoryk w aluminiowej obudowie",
        "price_tier": "budget",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    # Woda / Water
    {
        "name": "Sawyer Mini",
        "category": "water",
        "brand": "Sawyer",
        "model": "Mini",
        "description": "Kompaktowy filtr do wody, łatwy w transporcie",
        "price_tier": "budget",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Sawyer Squeeze",
        "category": "water",
        "brand": "Sawyer",
        "model": "Squeeze",
        "description": "Wydajny filtr do zastosowań outdoor",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Katadyn BeFree 3L",
        "category": "water",
        "brand": "Katadyn",
        "model": "BeFree 3L",
        "description": "Filtr grawitacyjny idealny na biwak / obóz",
        "price_tier": "premium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "LifeStraw Personal Water Filter",
        "category": "water",
        "brand": "LifeStraw",
        "model": "LifeStraw Personal Water Filter",
        "description": "Prosty filtr słomkowy do oczyszczania wody w terenie",
        "price_tier": "budget",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "LifeStraw Go 650 ml",
        "category": "water",
        "brand": "LifeStraw",
        "model": "Go 650 ml",
        "description": "Butelka z wbudowanym filtrem do wody, wygodna w użyciu",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    # Schronienie / Shelter
    {
        "name": "DD Hammocks 3×3 Tarp",
        "category": "shelter",
        "brand": "DD Hammocks",
        "model": "3×3 Tarp",
        "description": "Lekki tarp do wielu konfiguracji schronienia",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Snugpak Stratosphere",
        "category": "shelter",
        "brand": "Snugpak",
        "model": "Stratosphere",
        "description": "Kompaktowy bivy-shelter survivalowy",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "MSR Hubba Hubba",
        "category": "shelter",
        "brand": "MSR",
        "model": "Hubba Hubba",
        "description": "Lekki, dwumiejscowy namiot trekkingowy",
        "price_tier": "premium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    # Light
    {
        "name": "Olight i5R EOS",
        "category": "light",
        "brand": "Olight",
        "model": "i5R EOS",
        "description": "Kompaktowa latarka EDC",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Black Diamond Storm Headlamp",
        "category": "light",
        "brand": "Black Diamond",
        "model": "Storm",
        "description": "Czołówka outdoorowa z mocnym światłem, odporna na warunki",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Fenix PD35 V3.0",
        "category": "light",
        "brand": "Fenix",
        "model": "PD35 V3.0",
        "description": "Taktyczna latarka o dużej mocy i zasięgu",
        "price_tier": "premium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    # First Aid
    {
        "name": "Emergency Bandage 6\"",
        "category": "firstAid",
        "brand": "Emergency Bandage",
        "model": "6\"",
        "description": "Izraelski opatrunek do tamowania krwotoków",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "CAT GEN7 Tourniquet",
        "category": "firstAid",
        "brand": "CAT",
        "model": "GEN7",
        "description": "Profesjonalna staza uciskowa",
        "price_tier": "premium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    # Container / Other
    {
        "name": "Condor MA36 Admin Pouch",
        "category": "other",
        "brand": "Condor",
        "model": "MA36",
        "description": "Kieszeń organizer-pouch, dobra do EDC",
        "price_tier": "budget",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Maxpedition Falcon II",
        "category": "other",
        "brand": "Maxpedition",
        "model": "Falcon II",
        "description": "Solidny plecak EDC/outdoor z systemem MOLLE",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "5.11 Rush 24",
        "category": "other",
        "brand": "5.11",
        "model": "Rush 24",
        "description": "Wytrzymały, pojemny plecak taktyczny / survivalowy",
        "price_tier": "premium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    # Food
    {
        "name": "Clif Bar Chocolate Chip",
        "category": "food",
        "brand": "Clif Bar",
        "model": "Chocolate Chip",
        "description": "Energetyczny baton do szybkiego zastrzyku kalorii",
        "price_tier": "budget",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "LyoFood Beef Stroganoff",
        "category": "food",
        "brand": "LyoFood",
        "model": "Beef Stroganoff",
        "description": "Liofilizowany posiłek turystyczny",
        "price_tier": "premium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Menażka Primus Eta Power",
        "category": "food",
        "brand": "Primus",
        "model": "Eta Power",
        "description": "Lekka menażka do gotowania w terenie",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Racje NRG-5",
        "category": "food",
        "brand": "NRG-5",
        "model": "NRG-5",
        "description": "Wysokokaloryczne racje żywnościowe survivalowe",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    # Navigation
    {
        "name": "Rite in the Rain All-Weather Notebook",
        "category": "navigation",
        "brand": "Rite in the Rain",
        "model": "All-Weather",
        "description": "Notes odporny na wodę — idealny na wyprawy",
        "price_tier": "budget",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Suunto MC-2 Compass",
        "category": "navigation",
        "brand": "Suunto",
        "model": "MC-2",
        "description": "Precyzyjny kompas terenowy",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    # Communication
    {
        "name": "Fox 40 Classic Whistle",
        "category": "communication",
        "brand": "Fox 40",
        "model": "Classic Whistle",
        "description": "Głośny gwizdek ratunkowy, nie wymaga baterii",
        "price_tier": "budget",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "name": "Anker PowerCore 20100",
        "category": "communication",
        "brand": "Anker",
        "model": "PowerCore 20100",
        "description": "Duży powerbank przydatny w terenie",
        "price_tier": "mid",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
]
