"""Catalogue items seeder data.

This file contains the initial catalogue items to be seeded into the database.
Data is sourced from docs/plans/global-catalogue-items.md
"""

# Mapping of item names to image filenames
CATALOGUE_ITEM_IMAGES = {
    "Swedish FireSteel 2.0": "light_my_fire_firesteel_2.0.jpg",
    "5.11 Rush 24": "5.11_rush_24.png",
    "Black Diamond Storm Headlamp": "black_diamond_storm_450.jpg",
    "Fenix PD35 V3.0": "fenix_pd35v3_flashlight.webp",
    "Anker PowerCore 20100": "anker_powercore_20100.png",
    "Fiskars X7": "fiskars-x7.png",
    "Leatherman Wave+": "leatherman-wave-plus.png",
    "Leatherman Blast": "leatherman-blast.png",
    "Gorilla Tape": "gorilla-tape.png",
    "BAHCO 396-LAP": "bahco-laplander.jpg.png",
    "Victorinox Ranger": "Victorinox-Ranger.png",
    "Victorinox Alox Bantam - Silver": "Victorinox-Alox-Bantam-Silver.png",
    "Sawyer Mini": "sawyer-mini.png",
    "Sawyer Squeeze": "sawyer-squeeze-sp129.png",
    "LifeStraw Personal Water Filter": "lifestraw-personal.png",
    "LifeStraw Go 650 ml": "lifestraw-go-2.png",
    "CAT GEN7 Tourniquet": "CAT-GEN7-Tourniquet.png",
    "Condor MA36 Admin Pouch": "Condor-MA36-Admin-Pouch.png",
    "Snugpak Stratosphere": "Snugpak-Stratosphere.png",
    "Suunto MC-2 Compass": "Suunto-MC-2-Compass.png",
    "Racje NRG-5": "NRG-5.png",
    "DD Hammocks 3×3 Tarp": "DD-Hammocks-3×3-Tarp.png",
}

CATALOGUE_ITEMS = [
    # Ogień / Fire
    {
        "id": "01KBJXFP7WMDKNJ8HNMBW1CZZG",
        "name": "Swedish FireSteel 2.0",
        "category": "fire",
        "brand": "Light My Fire",
        "model": "Swedish FireSteel 2.0",
        "description": "Krzesiwo ferrocerowe, niezawodne w trudnych warunkach",
        "price_tier": "medium",
        "quality": "high",
        "weight": 50.0,
        "weight_unit": "g",
        "url": "https://lightmyfire.com/products/swedish-firesteel",
    },
    {
        "id": "01KBJXGQ87FGHRFQTVMP3YFSNG",
        "name": "BIC Classic Lighter",
        "category": "fire",
        "brand": "BIC",
        "model": "Classic",
        "description": "Prosta i tania zapalniczka jednorazowa",
        "price_tier": "low",
        "quality": "medium",
        "weight": 21.0,
        "weight_unit": "g",
        "url": "https://www.bicworld.com/en/products/details/1/bic-lighter",
    },
    # Noże / Narzędzia tnące
    {
        "id": "01KBJXH29HTYHNAD2QHR4VQ0H7",
        "name": "Fiskars X7",
        "category": "tools",
        "brand": "Fiskars",
        "model": "X7",
        "description": "Lekka, kompaktowa siekierka turystyczna / survivalowa",
        "price_tier": "low",
        "quality": "medium",
        "weight": 645.0,
        "weight_unit": "g",
        "url": "https://www.fiskars.com/en-us/products/gardening/axes/x7-splitting-axe-1000573",
    },
    # Narzędzia wielofunkcyjne
    {
        "id": "01KBJXH4VP0T1SAZADHD3KY0RY",
        "name": "Leatherman Wave+",
        "category": "tools",
        "brand": "Leatherman",
        "model": "Wave+",
        "description": "Uniwersalny multitool klasy premium",
        "price_tier": "high",
        "quality": "high",
        "weight": 8.5,
        "weight_unit": "oz",
        "url": "https://www.leatherman.com/wave-plus-831429.html",
    },
    {
        "id": "01KBJXH7904T9DT153977RWERA",
        "name": "Leatherman Blast",
        "category": "tools",
        "brand": "Leatherman",
        "model": "Blast",
        "description": "Solidny multitool z pełnym zestawem narzędzi",
        "price_tier": "medium",
        "quality": "high",
        "weight": 6.9,
        "weight_unit": "oz",
        "url": "https://www.leatherman.com/blast-831429.html",
    },
    {
        "id": "01KBJXHA4CVVWZJRSWDJ19F85C",
        "name": "Gerber E-Tool Folding Shovel",
        "category": "tools",
        "brand": "Gerber",
        "model": "E-Tool Folding Shovel",
        "description": "Składana saperka terenowa",
        "price_tier": "medium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXHCCSSKZWDFR4AB4H5DCV",
        "name": "Paracord 550 MIL-SPEC",
        "category": "tools",
        "brand": "Generic / MIL-SPEC",
        "model": "Paracord 550",
        "description": "Uniwersalna linka ratunkowa / survivalowa",
        "price_tier": "low",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXHEW5ECFZVXQFB4E539E5",
        "name": "Paracord (Badger / MIL-SPEC)",
        "category": "tools",
        "brand": "Badger",
        "model": "Paracord 550",
        "description": "Mocna linka survivalowa / ratunkowa",
        "price_tier": "low",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXHH4WF4NYD9HD3P955H9H",
        "name": "Gorilla Tape",
        "category": "tools",
        "brand": "Gorilla Tape",
        "model": "Gorilla Tape Standard",
        "description": "Uniwersalna, mocna taśma naprawcza do terenu",
        "price_tier": "low",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXHKTWG3VFP9WR006129C0",
        "name": "BAHCO 396-LAP",
        "category": "tools",
        "brand": "BAHCO",
        "model": "396-LAP",
        "description": "Składana piła ręczna, idealna do cięcia drewna w terenie",
        "price_tier": "medium",
        "quality": "high",
        "weight": 200.0,
        "weight_unit": "g",
        "url": "https://www.bahco.com/en_us/products/hand-tools/saws/folding-saws/396-lap-folding-saw.html",
    },
    {
        "id": "01KBJXHP7289P4VEDKSCAMYBJW",
        "name": "Victorinox Ranger",
        "category": "tools",
        "brand": "Victorinox",
        "model": "Ranger",
        "description": "Szwajcarski scyzoryk z wieloma funkcjami, idealny do outdoor",
        "price_tier": "medium",
        "quality": "high",
        "weight": 118.0,
        "weight_unit": "g",
        "url": "https://www.victorinox.com/global/en/products/Swiss-Army-Knives/Medium-Pocket-Knives/Ranger/p/1.3713",
    },
    {
        "id": "01KBJXHRQ0NKA5QAGHHC41YE4A",
        "name": "Victorinox Alox Bantam - Silver",
        "category": "tools",
        "brand": "Victorinox",
        "model": "Alox Bantam - Silver",
        "description": "Ultra-kompaktowy scyzoryk w aluminiowej obudowie",
        "price_tier": "low",
        "quality": "high",
        "weight": 29.0,
        "weight_unit": "g",
        "url": "https://www.victorinox.com/global/en/products/Swiss-Army-Knives/Small-Pocket-Knives/Alox-Bantam/p/0.6221",
    },
    # Woda / Water
    {
        "id": "01KBJXHWAA2WJPCWEWDQ1HMZ38",
        "name": "Sawyer Mini",
        "category": "water",
        "brand": "Sawyer",
        "model": "Mini",
        "description": "Kompaktowy filtr do wody, łatwy w transporcie",
        "price_tier": "low",
        "quality": "medium",
        "weight": 2.0,
        "weight_unit": "oz",
        "url": "https://sawyer.com/products/mini-water-filtration-system",
    },
    {
        "id": "01KBJXHYQ826J0HKQ21CK8CR6H",
        "name": "Sawyer Squeeze",
        "category": "water",
        "brand": "Sawyer",
        "model": "Squeeze",
        "description": "Wydajny filtr do zastosowań outdoor",
        "price_tier": "medium",
        "quality": "high",
        "weight": 3.0,
        "weight_unit": "oz",
        "url": "https://sawyer.com/products/squeeze-water-filtration-system",
    },
    {
        "id": "01KBJXJ16F5J1NYW6GZN2S906E",
        "name": "Katadyn BeFree 3L",
        "category": "water",
        "brand": "Katadyn",
        "model": "BeFree 3L",
        "description": "Filtr grawitacyjny idealny na biwak / obóz",
        "price_tier": "high",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXJ3P532DYZMJ0DK2K6MW1",
        "name": "LifeStraw Personal Water Filter",
        "category": "water",
        "brand": "LifeStraw",
        "model": "LifeStraw Personal Water Filter",
        "description": "Prosty filtr słomkowy do oczyszczania wody w terenie",
        "price_tier": "low",
        "quality": "medium",
        "weight": 46.0,
        "weight_unit": "g",
        "url": "https://www.lifestraw.com/products/lifestraw-personal-water-filter",
    },
    {
        "id": "01KBJXJ60YKWVB026N8YJ9TYPE",
        "name": "LifeStraw Go 650 ml",
        "category": "water",
        "brand": "LifeStraw",
        "model": "Go 650 ml",
        "description": "Butelka z wbudowanym filtrem do wody, wygodna w użyciu",
        "price_tier": "medium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
        "url": "https://www.lifestraw.com/products/lifestraw-go",
    },
    # Schronienie / Shelter
    {
        "id": "01KBJXJ89WTHT4WS6MPH83601A",
        "name": "DD Hammocks 3×3 Tarp",
        "category": "shelter",
        "brand": "DD Hammocks",
        "model": "3×3 Tarp",
        "description": "Lekki tarp do wielu konfiguracji schronienia",
        "price_tier": "medium",
        "quality": "high",
        "weight": 875.0,
        "weight_unit": "g",
        "url": "https://www.ddhammocks.com/product/3x3-tarp",
    },
    {
        "id": "01KBJXJAW5J9ZGT47V2262BEDR",
        "name": "Snugpak Stratosphere",
        "category": "shelter",
        "brand": "Snugpak",
        "model": "Stratosphere",
        "description": "Kompaktowy bivy-shelter survivalowy",
        "price_tier": "medium",
        "quality": "high",
        "weight": 1.13,
        "weight_unit": "kg",
    },
    {
        "id": "01KBJXJDA0BW8V8C8NCFGVM8BQ",
        "name": "MSR Hubba Hubba",
        "category": "shelter",
        "brand": "MSR",
        "model": "Hubba Hubba",
        "description": "Lekki, dwumiejscowy namiot trekkingowy",
        "price_tier": "high",
        "quality": "high",
        "weight": 1.601,
        "weight_unit": "kg",
        "url": "https://www.msrgear.com/tents/hubba-hubba-2-person-tent",
    },
    # Light
    {
        "id": "01KBJXJG4W8XTT9K3TPNHF10H9",
        "name": "Olight i5R EOS",
        "category": "light",
        "brand": "Olight",
        "model": "i5R EOS",
        "description": "Kompaktowa latarka EDC",
        "price_tier": "medium",
        "quality": "high",
        "weight": 60.0,
        "weight_unit": "g",
        "url": "https://www.olightstore.com/i5r-eos",
    },
    {
        "id": "01KBJXJJMZZYVFYJWRQS4MPGQP",
        "name": "Black Diamond Storm 450",
        "category": "light",
        "brand": "Black Diamond",
        "model": "Storm 450",
        "description": "Czołówka outdoorowa z mocnym światłem, odporna na warunki",
        "price_tier": "medium",
        "quality": "high",
        "weight": 92.0,
        "weight_unit": "g",
        "url": "https://www.blackdiamondequipment.com/en_US/headlamps-and-lanterns/storm-450-headlamp-BD620625.html",
    },
    {
        "id": "01KBJXJNER6NZPMWMVMNEF084H",
        "name": "Fenix PD35 V3.0",
        "category": "light",
        "brand": "Fenix",
        "model": "PD35 V3.0",
        "description": "Taktyczna latarka o dużej mocy i zasięgu",
        "price_tier": "high",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
        "url": "https://www.fenixlighting.com/product/pd35-v3-flashlight/",
    },
    # First Aid
    {
        "id": "01KBJXJR1XVTCHZFN6CG9A301C",
        "name": 'Emergency Bandage 6"',
        "category": "firstAid",
        "brand": "Emergency Bandage",
        "model": '6"',
        "description": "Izraelski opatrunek do tamowania krwotoków",
        "price_tier": "medium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXJT941E9K2RTM3C4G461B",
        "name": "CAT GEN7 Tourniquet",
        "category": "firstAid",
        "brand": "CAT",
        "model": "GEN7",
        "description": "Profesjonalna staza uciskowa",
        "price_tier": "high",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
        "url": "https://www.cat-tourniquets.com/products/c-a-t-gen-7",
    },
    # Container / Other
    {
        "id": "01KBJXJWG88FJRXF8297YYFW05",
        "name": "Condor MA36 Admin Pouch",
        "category": "other",
        "brand": "Condor",
        "model": "MA36",
        "description": "Kieszeń organizer-pouch, dobra do EDC",
        "price_tier": "low",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXJYS9SVWHKZ402ZF2358F",
        "name": "Maxpedition Falcon II",
        "category": "other",
        "brand": "Maxpedition",
        "model": "Falcon II",
        "description": "Solidny plecak EDC/outdoor z systemem MOLLE",
        "price_tier": "medium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXK1P9Z7DJ0TYR3AN5YRWS",
        "name": "5.11 Rush 24",
        "category": "other",
        "brand": "5.11",
        "model": "Rush 24",
        "description": "Wytrzymały, pojemny plecak taktyczny / survivalowy",
        "price_tier": "high",
        "quality": "high",
        "weight": 3.85,
        "weight_unit": "lb",
        "url": "https://www.511tactical.com/rush-24-backpack.html",
    },
    # Food
    {
        "id": "01KBJXK44TPQW7A9RHQH0WT147",
        "name": "Clif Bar Chocolate Chip",
        "category": "food",
        "brand": "Clif Bar",
        "model": "Chocolate Chip",
        "description": "Energetyczny baton do szybkiego zastrzyku kalorii",
        "price_tier": "low",
        "quality": "medium",
        "weight": 68.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXK6YK4F82T57WCXV5J47D",
        "name": "LyoFood Beef Stroganoff",
        "category": "food",
        "brand": "LyoFood",
        "model": "Beef Stroganoff",
        "description": "Liofilizowany posiłek turystyczny",
        "price_tier": "high",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXK97HRZVNG9MQ6R1BG1VY",
        "name": "Menażka Primus Eta Power",
        "category": "food",
        "brand": "Primus",
        "model": "Eta Power",
        "description": "Lekka menażka do gotowania w terenie",
        "price_tier": "medium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXKBHHGBW27PNM3EEBRMMN",
        "name": "Racje NRG-5",
        "category": "food",
        "brand": "NRG-5",
        "model": "NRG-5",
        "description": "Wysokokaloryczne racje żywnościowe survivalowe",
        "price_tier": "medium",
        "quality": "high",
        "weight": 500.0,
        "weight_unit": "g",
    },
    # Navigation
    {
        "id": "01KBJXKF6RS91JXKZQ0NBVFEVB",
        "name": "Rite in the Rain All-Weather Notebook",
        "category": "navigation",
        "brand": "Rite in the Rain",
        "model": "All-Weather",
        "description": "Notes odporny na wodę — idealny na wyprawy",
        "price_tier": "low",
        "quality": "medium",
        "weight": 0.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBJXKHNDWZ85HZZTG8DN0XVR",
        "name": "Suunto MC-2 Compass",
        "category": "navigation",
        "brand": "Suunto",
        "model": "MC-2",
        "description": "Precyzyjny kompas terenowy",
        "price_tier": "medium",
        "quality": "high",
        "weight": 0.0,
        "weight_unit": "g",
    },
    # Communication
    {
        "id": "01KBJXKM1SJXS2T8GG7R4CGDN6",
        "name": "Fox 40 Classic Whistle",
        "category": "communication",
        "brand": "Fox 40",
        "model": "Classic Whistle",
        "description": "Głośny gwizdek ratunkowy, nie wymaga baterii",
        "price_tier": "low",
        "quality": "medium",
        "weight": 0.01,
        "weight_unit": "oz",
    },
    {
        "id": "01KBJXKPDHSV3W2NNP222TVPZZ",
        "name": "Anker PowerCore 20100",
        "category": "communication",
        "brand": "Anker",
        "model": "PowerCore 20100",
        "description": "Duży powerbank przydatny w terenie",
        "price_tier": "medium",
        "quality": "high",
        "weight": 356.0,
        "weight_unit": "g",
        "url": "https://www.anker.com/products/a1271",
    },
    # New items from global-catalogue-items-v2.md
    {
        "id": "01KBQ9MKG500FXNVND2X3J4AYW",
        "name": "Mil-Tec Emergency Thermal Blanket (foil)",
        "category": "shelter",
        "brand": "Mil-Tec",
        "model": "Thermal Blanket",
        "description": "Lekka folia ratunkowa / koc termoizolacyjny – przydatna do ochrony przed wychłodzeniem lub jako awaryjne schronienie.",
        "price_tier": "low",
        "quality": "medium",
        "weight": 50.0,
        "weight_unit": "g",
        "url": "https://www.mil-tec.com/en/emergency-thermal-blanket",
    },
    {
        "id": "01KBQ9MKG500FXNVND2X3J4AYX",
        "name": "CNOC Vecto Collapsible Water Bottle 1L",
        "category": "water",
        "brand": "CNOC",
        "model": "Vecto 1L",
        "description": "Składana, lekka butelka na wodę – dobra do noszenia przefiltrowanej wody lub transportu wody pitnej.",
        "price_tier": "low",
        "quality": "medium",
        "weight": 40.0,
        "weight_unit": "g",
        "url": "https://cnocoutdoors.com/products/vecto-collapsible-water-container",
    },
    {
        "id": "01KBQ9MKG500FXNVND2X3J4AYY",
        "name": "Aquamira Water Purification Tablets (30 tabs)",
        "category": "water",
        "brand": "Aquamira",
        "model": "Water Treatment Tablets",
        "description": "Tabletki do chemicznego uzdatniania wody – backup lub alternatywa do filtra.",
        "price_tier": "low",
        "quality": "medium",
        "weight": 30.0,
        "weight_unit": "g",
        "url": "https://www.aquamira.com/products/water-treatment-tablets",
    },
    {
        "id": "01KBQ9MKG500FXNVND2X3J4AYZ",
        "name": "GSI Outdoors Stainless Steel Cup 700 ml",
        "category": "other",
        "brand": "GSI Outdoors",
        "model": "Stainless Steel Cup 700 ml",
        "description": "Metalowy kubek / menażka – do gotowania wody lub posiłków w terenie.",
        "price_tier": "low",
        "quality": "medium",
        "weight": 150.0,
        "weight_unit": "g",
        "url": "https://www.gsioutdoors.com/stainless-steel-cup.html",
    },
    {
        "id": "01KBQ9MKG500FXNVND2X3J4AZ0",
        "name": "UCO Stormproof Matches – 25 szt.",
        "category": "fire",
        "brand": "UCO",
        "model": "Stormproof Matches",
        "description": "Wodoodporne, wiatroszczelne zapałki – dobre zabezpieczenie awaryjne dla ognia.",
        "price_tier": "low",
        "quality": "medium",
        "weight": 25.0,
        "weight_unit": "g",
        "url": "https://www.ucogear.com/products/stormproof-matches",
    },
    {
        "id": "01KBQ9MKG500FXNVND2X3J4AZ1",
        "name": "Compact Duct Tape (10 m roll)",
        "category": "tools",
        "brand": "Generic",
        "model": "10m Duct Tape",
        "description": "Uniwersalna taśma naprawcza – przydatna do napraw, improwizacji, uszczelniania, zabezpieczeń.",
        "price_tier": "low",
        "quality": "medium",
        "weight": 100.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBQ9MKG500FXNVND2X3J4AZ2",
        "name": "Metal Spork (Titanium / Stainless)",
        "category": "tools",
        "brand": "Generic",
        "model": "Folding Spork",
        "description": "Składana łyżko-widelec – lekki element do jedzenia / gotowania w terenie.",
        "price_tier": "low",
        "quality": "medium",
        "weight": 25.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBQ9MKG500FXNVND2X3J4AZ3",
        "name": "Emergency Poncho (nylon / waterproof)",
        "category": "shelter",
        "brand": "Generic",
        "model": "Emergency Poncho",
        "description": "Lekki wodoodporny poncho – zabezpieczenie przed deszczem / wilgocią, może służyć jako prowizoryczne schronienie.",
        "price_tier": "low",
        "quality": "medium",
        "weight": 120.0,
        "weight_unit": "g",
    },
    {
        "id": "01KBQ9MKG500FXNVND2X3J4AZ4",
        "name": "Olight i3T EOS 2",
        "category": "light",
        "brand": "Olight",
        "model": "i3T 2 EOS",
        "description": "Mała, niezawodna latarka EDC na jedną baterię AAA (180 lm, momentary tail switch).",
        "price_tier": "medium",
        "quality": "high",
        "price": 25.0,
        "price_currency": "USD",
        "color": "Black",
        "weight": 40.0,
        "weight_unit": "g",
        "url": "https://www.olightstore.com/i3t-eos",
    },
    {
        "id": "01KBQ9MKG500FXNVND2X3J4AZ5",
        "name": "Light My Fire Swedish FireSteel 2.0",
        "category": "fire",
        "brand": "Light My Fire",
        "model": "Swedish FireSteel 2.0",
        "description": "Klasyczne ferro rod — iskry 3000°C, bardzo niezawodne w warunkach terenowych.",
        "price_tier": "medium",
        "quality": "high",
        "price": 15.0,
        "price_currency": "USD",
        "weight": 50.0,
        "weight_unit": "g",
        "url": "https://lightmyfire.com/products/swedish-firesteel",
    },
    {
        "id": "01KBQ9MKG50801WW461XE4JJA4",
        "name": "Victorinox Huntsman",
        "category": "tools",
        "brand": "Victorinox",
        "model": "Huntsman",
        "description": "Klasyczny scyzoryk z piłką, nożyczkami i ostrzem — świetny do EDC i outdoor.",
        "price_tier": "medium",
        "quality": "high",
        "price": 45.0,
        "price_currency": "USD",
        "color": "Red",
        "weight": 97.0,
        "weight_unit": "g",
        "url": "https://www.victorinox.com/global/en/products/Swiss-Army-Knives/Medium-Pocket-Knives/Huntsman/p/1.3713",
    },
    {
        "id": "01KBQ9MKG60801WW461XE4JJA5",
        "name": "Ferrocerium Rod 8 mm",
        "category": "fire",
        "brand": "Generic",
        "model": "Ferro Rod 8mm",
        "description": "Standardowy ferro rod 8 mm — lekka alternatywa do większych prętów.",
        "price_tier": "low",
        "quality": "medium",
        "price": 8.0,
        "price_currency": "USD",
        "weight": 35.0,
        "weight_unit": "g",
        "url": "https://www.amazon.com",
    },
    {
        "id": "01KBQ9MKG60801WW461XE4JJA6",
        "name": "Rite in the Rain All-Weather Notepad 3x5",
        "category": "other",
        "brand": "Rite in the Rain",
        "model": "3x5 Top-Spiral",
        "description": "Notes wodoodporny — działa w deszczu, śniegu, błocie; klasyk w survivalu.",
        "price_tier": "low",
        "quality": "medium",
        "price": 6.0,
        "price_currency": "USD",
        "color": "Yellow",
        "weight": 70.0,
        "weight_unit": "g",
        "url": "https://riteintherain.com/products/top-spiral-notepad-3x5",
    },
    {
        "id": "01KBQ9MKG60801WW461XE4JJA7",
        "name": "Sharpie Permanent Marker (Fine Tip)",
        "category": "other",
        "brand": "Sharpie",
        "model": "Fine Black",
        "description": "Marker permanentny — podpisywanie, notatki awaryjne, oznaczanie sprzętu.",
        "price_tier": "low",
        "quality": "medium",
        "price": 2.0,
        "price_currency": "USD",
        "color": "Black",
        "weight": 9.0,
        "weight_unit": "g",
        "url": "https://www.sharpie.com",
    },
    {
        "id": "01KBQ9MKG60801WW461XE4JJA8",
        "name": "Fenix E01 V2.0",
        "category": "light",
        "brand": "Fenix",
        "model": "E01 V2.0",
        "description": "Ultra-lekka latarka AAA, idealna jako backup.",
        "price_tier": "medium",
        "quality": "high",
        "price": 20.0,
        "price_currency": "USD",
        "color": "Black",
        "weight": 13.0,
        "weight_unit": "g",
        "url": "https://www.fenixlighting.com/product/e01-v2-flashlight/",
    },
]
