import type {
  TGearItemCategory,
  TGearItemPriority,
  TGearItemQuality,
  TGearItemStatus,
  TGearWeightUnit,
} from '../types/gear.types'

export interface IExampleSetItem {
  nameKey: string // Translation key for the item name
  category: TGearItemCategory
  weight: number
  weightUnit: TGearWeightUnit
  quantity?: number
  priority?: TGearItemPriority
  status?: TGearItemStatus
  brand?: string
  notesKey?: string // Translation key for notes
  color?: string // Item color
  price?: number // Approximate price in USD
  currency?: string // Currency code (default: USD)
  url?: string // Product URL
  quality?: TGearItemQuality // Price tier / quality
  consumable?: boolean // Item is consumed/used up
}

// Fire Pouch items
export const firePouchItems: IExampleSetItem[] = [
  {
    nameKey: 'gear.sampleSet.items.lightMyFireFiresteel',
    category: 'fire',
    weight: 28,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'Light My Fire',
    notesKey: 'gear.sampleSet.items.lightMyFireFiresteel.notes',
    color: 'Orange',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.coghlansTinderQuik',
    category: 'fire',
    weight: 15,
    weightUnit: 'g',
    quantity: 3,
    priority: 'high',
    status: 'owned',
    brand: 'Coghlan\'s',
    notesKey: 'gear.sampleSet.items.coghlansTinderQuik.notes',
    color: 'Yellow',
    price: 5,
    currency: 'USD',
    quality: 'medium',
    consumable: true,
  },
  {
    nameKey: 'gear.sampleSet.items.bicLighter',
    category: 'fire',
    weight: 12,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'BIC',
    notesKey: 'gear.sampleSet.items.bicLighter.notes',
    color: 'Red',
    price: 2,
    currency: 'USD',
    quality: 'low',
    consumable: true,
  },
  {
    nameKey: 'gear.sampleSet.items.ucoStormproofMatches',
    category: 'fire',
    weight: 25,
    weightUnit: 'g',
    quantity: 1,
    priority: 'medium',
    status: 'owned',
    brand: 'UCO',
    notesKey: 'gear.sampleSet.items.ucoStormproofMatches.notes',
    color: 'Orange',
    price: 8,
    currency: 'USD',
    quality: 'high',
    consumable: true,
  },
]

// Bug Out Bag items
export const bugOutBagItems: IExampleSetItem[] = [
  {
    nameKey: 'gear.sampleSet.items.moraknivCompanion',
    category: 'blades',
    weight: 120,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'Morakniv',
    notesKey: 'gear.sampleSet.items.moraknivCompanion.notes',
    color: 'Orange',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.leathermanWave',
    category: 'tools',
    weight: 241,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'Leatherman',
    notesKey: 'gear.sampleSet.items.leathermanWave.notes',
    color: 'Silver',
    price: 120,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.fenixPD36R',
    category: 'light',
    weight: 145,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'Fenix',
    notesKey: 'gear.sampleSet.items.fenixPD36R.notes',
    color: 'Black',
    price: 90,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.adventureMedicalKitsUltralight',
    category: 'firstAid',
    weight: 340,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'Adventure Medical Kits',
    notesKey: 'gear.sampleSet.items.adventureMedicalKitsUltralight.notes',
    color: 'Red',
    price: 25,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.paracord550',
    category: 'tools',
    weight: 50,
    weightUnit: 'g',
    quantity: 1,
    priority: 'high',
    status: 'owned',
    brand: 'Generic',
    notesKey: 'gear.sampleSet.items.paracord550.notes',
    color: 'Black',
    price: 8,
    currency: 'USD',
    quality: 'medium',
  },
  {
    nameKey: 'gear.sampleSet.items.lifestrawPersonal',
    category: 'water',
    weight: 46,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'LifeStraw',
    notesKey: 'gear.sampleSet.items.lifestrawPersonal.notes',
    color: 'Blue',
    price: 20,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.solEmergencyBivvy',
    category: 'shelter',
    weight: 85,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'SOL (Survive Outdoors Longer)',
    notesKey: 'gear.sampleSet.items.solEmergencyBivvy.notes',
    color: 'Orange',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
]

// Bug Out Bag fire pouch items (nested container)
export const bugOutBagFirePouchItems: IExampleSetItem[] = [
  {
    nameKey: 'gear.sampleSet.items.lightMyFireFiresteel',
    category: 'fire',
    weight: 28,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'Light My Fire',
    color: 'Orange',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.bicLighter',
    category: 'fire',
    weight: 12,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'BIC',
    color: 'Red',
    price: 2,
    currency: 'USD',
    quality: 'low',
    consumable: true,
  },
  {
    nameKey: 'gear.sampleSet.items.coghlansTinderQuik',
    category: 'fire',
    weight: 15,
    weightUnit: 'g',
    quantity: 2,
    priority: 'high',
    status: 'owned',
    brand: 'Coghlan\'s',
    color: 'Yellow',
    price: 5,
    currency: 'USD',
    quality: 'medium',
    consumable: true,
  },
]

// EDC items
export const edcItems: IExampleSetItem[] = [
  {
    nameKey: 'gear.sampleSet.items.victorinoxClassicSD',
    category: 'blades',
    weight: 21,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'Victorinox',
    notesKey: 'gear.sampleSet.items.victorinoxClassicSD.notes',
    color: 'Red',
    price: 20,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.olightI3TEOS',
    category: 'light',
    weight: 12,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'Olight',
    notesKey: 'gear.sampleSet.items.olightI3TEOS.notes',
    color: 'Black',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.zippoLighter',
    category: 'fire',
    weight: 55,
    weightUnit: 'g',
    priority: 'medium',
    status: 'owned',
    brand: 'Zippo',
    notesKey: 'gear.sampleSet.items.zippoLighter.notes',
    color: 'Chrome',
    price: 20,
    currency: 'USD',
    quality: 'high',
    consumable: true,
  },
  {
    nameKey: 'gear.sampleSet.items.fieldNotesNotebook',
    category: 'tools',
    weight: 80,
    weightUnit: 'g',
    priority: 'low',
    status: 'owned',
    brand: 'Field Notes',
    notesKey: 'gear.sampleSet.items.fieldNotesNotebook.notes',
    color: 'Tan',
    price: 10,
    currency: 'USD',
    quality: 'medium',
    consumable: true,
  },
  {
    nameKey: 'gear.sampleSet.items.fisherSpacePen',
    category: 'tools',
    weight: 8,
    weightUnit: 'g',
    priority: 'medium',
    status: 'owned',
    brand: 'Fisher',
    notesKey: 'gear.sampleSet.items.fisherSpacePen.notes',
    color: 'Black',
    price: 25,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.ankerPowerCore10000',
    category: 'communication',
    weight: 180,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'Anker',
    notesKey: 'gear.sampleSet.items.ankerPowerCore10000.notes',
    color: 'Black',
    price: 30,
    currency: 'USD',
    quality: 'high',
  },
]

